/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ks_testndk_JNITest */

#ifndef _Included_com_ks_testndk_JNITest
#define _Included_com_ks_testndk_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ks_testndk_JNITest
 * Method:    inits
 * Signature: ()v
 *
JNIEXPORT void JNICALL Java_com_ks_testndk_JNITest_inits
  (JNIEnv *, jobject);
  */
/*
 * Class:     com_ks_testndk_JNITest
 * Method:    deleteGlobalRefs
 * Signature: ()v
 */
JNIEXPORT void JNICALL Java_com_ks_testndk_JNITest_finsh
  (JNIEnv *, jobject);

/*
 * Class:     com_ks_testndk_JNITest
 * Method:    add
 * Signature: (II)I

JNIEXPORT jint JNICALL Java_com_ks_testndk_JNITest_add
  (JNIEnv *, jobject, jint, jint);*/

/*
 * Class:     com_ks_testndk_JNITest
 * Method:    getHello
 * Signature: ()Ljava/lang/String;

JNIEXPORT jstring JNICALL Java_com_ks_testndk_JNITest_getHello
  (JNIEnv *, jobject); */

/*
 * Class:     com_ks_testndk_JNITest
 * Method:    getBitmap
 * Signature: ([ILandroid/graphics/Bitmap;Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_ks_testndk_JNITest_getBitmapNew
  (JNIEnv *, jobject, jintArray, jobject, jobject);
/*
 * Class:     com_ks_testndk_JNITest
 * Method:    getBitmap
 * Signature: ([ILandroid/graphics/Bitmap;Landroid/graphics/Bitmap;)v;
 */
JNIEXPORT void JNICALL Java_com_ks_testndk_JNITest_getBitmapOrl
  (JNIEnv *, jobject, jintArray, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
