/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_minilzo_common_LZOjni */

#ifndef _Included_org_minilzo_common_LZOjni
#define _Included_org_minilzo_common_LZOjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_minilzo_common_LZOjni
 * Method:    LZOCompress
 * Signature: ([BI[B[I)I
 */
JNIEXPORT jint JNICALL Java_org_minilzo_common_LZOjni_LZOCompress
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jintArray);

/*
 * Class:     org_minilzo_common_LZOjni
 * Method:    LZODecompress
 * Signature: ([BI[B[I)I
 */
JNIEXPORT jint JNICALL Java_org_minilzo_common_LZOjni_LZODecompress
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jintArray);

/*
 * Class:     org_minilzo_common_LZOjni
 * Method:    LZODecompress_safe
 * Signature: ([BI[B[I)I
 */
JNIEXPORT jint JNICALL Java_org_minilzo_common_LZOjni_LZODecompress_1safe
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
